[project]
name = "trends"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "y78y7878", email = "y78y7878@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "apscheduler>=3.11.3",
    "beautifulsoup4>=4.15.0",
    "cloudscraper>=1.2.71",
    "curl-cffi>=0.16.1",
    "feedparser>=6.0.14",
    "google-genai>=2.20.0",
    "google-generativeai>=0.8.6",
    "jieba>=0.42.1",
    "ollama>=0.6.2",
    "pandas>=3.0.5",
    "playwright>=1.62.0",
    "pyarrow>=25.0.1",
    "pymysql>=1.2.0",
    "python-dateutil>=2.9.0.post0",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
    "schedule>=1.2.2",
    "snowflake-connector-python>=4.7.3",
    "snowflake-snowpark-python>=1.54.0",
    "sqlalchemy>=2.1.1",
    "yfinance>=1.7.0",
]

[project.scripts]
trends = "trends:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
